// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8m4NE6qk7dEqugMTTWA6ezN9ZPHNEtYI',
    appId: '1:739582942655:web:fb43675d9f2cc1a8ce150a',
    messagingSenderId: '739582942655',
    projectId: 'finalprojpc',
    authDomain: 'finalprojpc.firebaseapp.com',
    storageBucket: 'finalprojpc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUocp15WGg4vqVeXQUhzg3Zmq0Cq97rnk',
    appId: '1:739582942655:android:196f8cbf20db2720ce150a',
    messagingSenderId: '739582942655',
    projectId: 'finalprojpc',
    storageBucket: 'finalprojpc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6s8DDoWCsD75r4QMZAB8GKIA7j1Sg_aM',
    appId: '1:739582942655:ios:a6534dca291eba07ce150a',
    messagingSenderId: '739582942655',
    projectId: 'finalprojpc',
    storageBucket: 'finalprojpc.appspot.com',
    iosBundleId: 'com.example.finalprojectCst9l',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6s8DDoWCsD75r4QMZAB8GKIA7j1Sg_aM',
    appId: '1:739582942655:ios:379f18b939aac5e6ce150a',
    messagingSenderId: '739582942655',
    projectId: 'finalprojpc',
    storageBucket: 'finalprojpc.appspot.com',
    iosBundleId: 'com.example.finalprojectCst9l.RunnerTests',
  );
}
